github-repository: "git@github.com:srganesh/pal-tracker.git"
github-private-key: |-
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA3AVVSABaCobs70YrZKBLXCCC70R2ZtgzvJsmx7LhxpT7ggHK
    Q63+bybPyIghtITvvPZiEbj59bkxeVv1jVIFErgfyPMM7jAn78jjX51jT7qXeKp0
    tfi2Q9S7wjTVrBCu3LTV1+wyhocMmrmGqtDA9Pmd3M3vSwgh4YBlvrRo3s599O3h
    zvzjb+X8agX3rlmq1fJD+3cYZErciymTVHN3kOC1DOZ+EPynkBJfJFhKiDEm9Fcp
    FOLMvuVGSqY+RL5aDHt0sk/Q/cl8Ic9EpFMVDxnGA7PWg4h7mVwFG6RARReFii5w
    waKFO4erwbn2wrt4agBbubNN3pmJDe0/JOSecQIDAQABAoIBAQDar0ZTeV4FhpQr
    QvBQZO5iVEIv9TlGAXBy7zc9V/QGf//3+TWDzYXODqKJq5zsoxDyHWXePZ/cd0TQ
    XfGTlElMkMuu3L0mZaDcOSyd1X5nOYviOHImiF0I0IIKhp82FaLn5amCotaZVdPW
    Wb6bOz/+fbhFRj6osh2S2B7IzOJLSNRYjuKnEeLBhFdm5+sdUYRyLaCrNEA05O5O
    RRqRYkG1tz+NE1ccSwLFIjAJ3vLOEY7etwhpRm5v10ftW99Kgh8ihFZ+RaXp1Kq8
    LId4lfRjG/slak6BElXTOD+tI3WsGcCkLKcad+lvKG5uSDTA7xTDZGX6kQNXZof4
    Yw1OMQKtAoGBAPY2g+YLa4YrKctmOK5MLybwhbwPGQE5KJEUD3eEzsXC/j9NGoIS
    2xp0JYK1Kk2sFIB+bFtBU1uXhY7KvibxrNEK9X0eTp+0GsfmNy93BX+xx6GATScT
    +nneN+PfFwESEKuWTHSjjdjIv/RTGaQrV1i2CtKYG3FPu+2/SZ8ktSi3AoGBAOTE
    SNsuFQGXKOq0hQRJxw/m2KnEBJj5Sduec7jx1eUCUdEsQEgonU/4+LKeRgh5Gr+S
    lly/5RpIYjCRA9KuPID/d03UJocAIA1yGlmMN1jogJ1TW7qGX43Ly+J93GQfun/O
    KC+09qT6H71ZFkh8lLZbHZjjD+XMyMGaG6NsP7oXAoGADdNB1MkPYJlL33/97suY
    WjdnSwgN/2OWQ488zxlGAxTP8f4CXwtwAixDbvN9TJ89B3oR243vgFUhysLXqpgn
    fBWBc2UgRRd36YGj16Z3SJRTAV6S9n7Isc8olEMSp5y8EuZ9pI8KiAG9xZpk9jL4
    1KJkOS8RW2t+wfrbx3PoOEECgYB2fJOfskZ/BGPU7JrYlb3cppwhkb0v3i466d7W
    M6utaX4m8Nx6g063VSS6nu93BAKupqXqdBmde1AgB3wLauM7jRWl4fPyiEYRsL+l
    EdK44fN7iOlBusdTEfMP5FB6K1TVTVnTG8+Ds2ktES9Ra/U6Xgb+YNyjEWYJoGAg
    TLjVEQKBgQD1P5gn0oXbL4YqaYup0P9NQ2Z95+M3YlE07f0AX9WYbCRopN/LpIbp
    kDXX7/+cORL0n9nl2aHCg0NsGHSmKuJOz7ZM3tSAwL6xlYe6lGpHXBrmfPly+af8
    Sf25I1LQTiL9Ri7A0vW1wwRnlq5YCUPsyoAhxUuEwv+piaSnb7QOhQ==
    -----END RSA PRIVATE KEY-----

aws-bucket: "student-artifacts-watters"
aws-access-key-id: "AKIAIBR6HWLSXEDQ47AQ"
aws-secret-access-key: "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"
cf-api-url: "https://apps.sys.evans.pal.pivotal.io/"
cf-username: "srganesh@hcl.com"
cf-password: "vh5fs8p8"
cf-org: "srinivasaragavan-ganesan"
